name: FinalBuildkite

on:
  workflow_run:
    workflows: [CodeQL]
    types: [in_progress]
jobs:
  sonarScan:
    runs-on: ubuntu-latest
    steps:
      - uses: haya14busa/action-workflow_run-status@v1
      - uses: actions/checkout@v2
      - name: Trigger Sonar Scan
        id: build
        uses: "buildkite/trigger-pipeline-action@v2.0.0"
        with:
          buildkite_api_access_token: ${{ secrets.BUILD_KITE_WRITE_TOKEN }}
          pipeline: "nnnnnnnnnnnn/notwell"
      - name: Get Build Kite URL
        run: |
          echo "buildkite link is: ${{ steps.build.outputs.url }}"
      - name: Waitting Buildkite Artifacts
        id: download
        uses: EnricoMi/download-buildkite-artifact-action@v1
        with:
          buildkite_token: ${{ secrets.BUILD_KITE_READ_TOKEN }}
          buildkite_build_url: ${{ steps.build.outputs.url }}
          ignore_build_states: blocked,canceled,skipped,not_run
          ignore_job_states: timed_out,failed
          output_path: artifacts
      - name: Check Result
        if: steps.download.outputs.build-state != 'passed'
        run: |
          echo "failed !!!!"
          echo "buildkite result is:  ${{ steps.download.outputs.build-state }}"
          exit 1
  debianUnitTest:
    runs-on: ubuntu-latest
    steps:
      - uses: haya14busa/action-workflow_run-status@v1
      - uses: actions/checkout@v2
      - name: Trigger Debian Unit Test
        id: build
        uses: "buildkite/trigger-pipeline-action@v2.0.0"
        with:
          buildkite_api_access_token: ${{ secrets.BUILD_KITE_WRITE_TOKEN }}
          pipeline: "nnnnnnnnnnnn/notwell1"
      - name: Get Build Kite URL
        run: |
          echo "buildkite link is: ${{ steps.build.outputs.url }}"
      - name: Waitting Buildkite Artifacts
        id: download
        uses: EnricoMi/download-buildkite-artifact-action@v1
        with:
          buildkite_token: ${{ secrets.BUILD_KITE_READ_TOKEN }}
          buildkite_build_url: ${{ steps.build.outputs.url }}
          ignore_build_states: blocked,canceled,skipped,not_run
          ignore_job_states: timed_out,failed
          output_path: artifacts
      - name: Check Result
        if: steps.download.outputs.build-state != 'passed'
        run: |
          echo "failed !!!!"
          echo "buildkite result is:  ${{ steps.download.outputs.build-state }}"
          exit 1
  centosUnitTest:
    runs-on: ubuntu-latest
    steps:
      - uses: haya14busa/action-workflow_run-status@v1
      - uses: actions/checkout@v2
      - name: Trigger Centos Unit Test
        id: build
        uses: "buildkite/trigger-pipeline-action@v2.0.0"
        with:
          buildkite_api_access_token: ${{ secrets.BUILD_KITE_WRITE_TOKEN }}
          pipeline: "nnnnnnnnnnnn/notwell"
      - name: Waitting Buildkite Artifacts
        id: download
        uses: EnricoMi/download-buildkite-artifact-action@v1
        with:
          buildkite_token: ${{ secrets.BUILD_KITE_READ_TOKEN }}
          buildkite_build_url: ${{ steps.build.outputs.url }}
          ignore_build_states: blocked,canceled,skipped,not_run
          ignore_job_states: timed_out,failed
          output_path: artifacts
      - name: Check Result
        if: steps.download.outputs.build-state != 'passed'
        run: |
          echo "failed !!!!"
          echo "buildkite result is:  ${{ steps.download.outputs.build-state }}"
          exit 1
  ubuntuUnitTest:
    name: Ubuntu Unit Test
    runs-on: ubuntu-latest
    steps:
      - uses: haya14busa/action-workflow_run-status@v1
      - uses: actions/checkout@v2
      - name: Trigger Ubuntu Unit Test
        id: build
        uses: "buildkite/trigger-pipeline-action@v2.0.0"
        with:
          buildkite_api_access_token: ${{ secrets.BUILD_KITE_WRITE_TOKEN }}
          pipeline: "nnnnnnnnnnnn/notwell1"
      - name: Waitting Buildkite Artifacts
        id: download
        uses: EnricoMi/download-buildkite-artifact-action@v1
        with:
          buildkite_token: ${{ secrets.BUILD_KITE_READ_TOKEN }}
          buildkite_build_url: ${{ steps.build.outputs.url }}
          ignore_build_states: blocked,canceled,skipped,not_run
          ignore_job_states: timed_out,failed
          output_path: artifacts
      - name: Check Result
        if: steps.download.outputs.build-state != 'passed'
        run: |
          echo "failed !!!!"
          echo "buildkite result is:  ${{ steps.download.outputs.build-state }}"
          exit 1
  apiSmokeTesting:
    name: API Smoke Testing
    runs-on: ubuntu-latest
    steps:
      - uses: haya14busa/action-workflow_run-status@v1
      - uses: actions/checkout@v2
      - name: Trigger API Smoke Testing
        id: build
        uses: "buildkite/trigger-pipeline-action@v2.0.0"
        with:
          buildkite_api_access_token: ${{ secrets.BUILD_KITE_WRITE_TOKEN }}
          pipeline: "nnnnnnnnnnnn/notwell"
      - name: Waitting Buildkite Artifacts
        id: download
        uses: EnricoMi/download-buildkite-artifact-action@v1
        with:
          buildkite_token: ${{ secrets.BUILD_KITE_READ_TOKEN }}
          buildkite_build_url: ${{ steps.build.outputs.url }}
          ignore_build_states: blocked,canceled,skipped,not_run
          ignore_job_states: timed_out,failed
          output_path: artifacts
      - name: Check Result
        if: steps.download.outputs.build-state != 'passed'
        run: |
          echo "failed !!!!"
          echo "buildkite result is:  ${{ steps.download.outputs.build-state }}"
          exit 1