name: "SetStatus"

on:
  push:
    branches: [ 'develop', 'master', 'release_**' ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ 'develop' ]

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    steps:
    - name: Get PR branch
      uses: xt0rted/pull-request-comment-branch@v2
      id: comment-branch
    - name: Check Permission
      uses: myrotvorets/set-commit-status-action@master
      with:
        sha: ${{ steps.comment-branch.outputs.head_sha }}
        token: ${{ secrets.GITHUB_TOKEN }}
        allowForks: true
        status: pending
    - name: Set commit status as pending
      uses: myrotvorets/set-commit-status-action@master
      with:
        sha: ${{ steps.comment-branch.outputs.head_sha }}
        token: ${{ secrets.GITHUB_TOKEN }}
        allowForks: true
        status: pending
    - name: Set final commit status
      uses: myrotvorets/set-commit-status-action@master
      if: always()
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        status: ${{ job.status }}

