name: "SetStatus"

on:
  push:
    branches: [ 'develop', 'master', 'release_**' ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ 'develop' ]

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    steps:
    - name: Set commit status as pending
      uses: myrotvorets/set-commit-status-action@master
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        status: pending
        context: Publish NPM package
    - name: Set final commit status
      uses: myrotvorets/set-commit-status-action@master
      if: always()
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        status: ${{ job.status }}
        context: Publish NPM package

